/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
        colors: {
            "surface": "#0c1324",
            "on-surface-variant": "#bec8d2",
            "on-tertiary-fixed": "#23005c",
            "tertiary-fixed-dim": "#d0bcff",
            "surface-tint": "#89ceff",
            "secondary-fixed": "#6ffbbe",
            "on-error": "#690005",
            "inverse-on-surface": "#2a3043",
            "surface-bright": "#33394c",
            "outline-variant": "#3e4850",
            "on-secondary-container": "#00311f",
            "on-surface": "#dce1fb",
            "surface-container-lowest": "#070d1f",
            "surface-container-highest": "#2e3447",
            "inverse-surface": "#dce1fb",
            "primary-fixed": "#c9e6ff",
            "on-primary-fixed": "#001e2f",
            "primary-container": "#0ea5e9",
            "on-primary": "#00344d",
            "surface-container-low": "#151b2d",
            "error": "#ffb4ab",
            "on-secondary-fixed-variant": "#005236",
            "tertiary-container": "#a986ff",
            "on-background": "#dce1fb",
            "on-primary-container": "#003751",
            "secondary-container": "#00a572",
            "on-secondary": "#003824",
            "outline": "#88929b",
            "on-tertiary-fixed-variant": "#5516be",
            "surface-container": "#191f31",
            "on-tertiary-container": "#3e0097",
            "inverse-primary": "#006591",
            "tertiary-fixed": "#e9ddff",
            "on-tertiary": "#3c0091",
            "surface-container-high": "#23293c",
            "primary": "#89ceff",
            "primary-fixed-dim": "#89ceff",
            "surface-variant": "#2e3447",
            "secondary": "#4edea3",
            "on-error-container": "#ffdad6",
            "tertiary": "#d0bcff",
            "background": "#0c1324",
            "error-container": "#93000a",
            "secondary-fixed-dim": "#4edea3",
            "surface-dim": "#0c1324",
            "on-secondary-fixed": "#002113",
            "on-primary-fixed-variant": "#004c6e",
            
            // Workspace specific palette overrides as requested
            "slate-950": "#020617",
            "slate-900": "#0f172a",
            "slate-800": "#1e293b",
            "wmo-emerald": "#10b981",
            "wmo-amber": "#f59e0b",
            "wmo-skyblue": "#38bdf8",
            "wmo-violet": "#8b5cf6",
            "wmo-rose": "#f43f5e"
        },
        fontFamily: {
            "body-sm": ["Inter", "sans-serif"],
            "data-mono-lg": ["JetBrains Mono", "monospace"],
            "label-caps": ["JetBrains Mono", "monospace"],
            "display-lg": ["Inter", "sans-serif"],
            "headline-md": ["Inter", "sans-serif"],
            "data-table": ["JetBrains Mono", "monospace"]
        },
    },
  },
  plugins: [],
}
